services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 512M
